Add zfs uefi
nix-community/nixos-install-scripts pull request #7
Opened 2021-03-11 03:52 UTC by happysalada

This adds a script for hetzner dedicated to enable running on zfs.
Regarding uefi, it should work but I haven't tested it.
https://docs.hetzner.com/robot/dedicated-server/operating-systems/efi-system-partition/
I'm afraid enabling uefi from nix will make the boot fail.

To clarify, the script works as is with BIOS boot. It needs to be tested and modified a bit for uefi to work. I was thinking of merging this as is, and let somebody else (future me maybe) finish the uefi part.

It took me quite a while to figure out everything (of course thanks to the base script). I thought in consequence that other people might want it. If people disagree that this is valuable, I'm happy to close the PR.

2021-03-11 03:53 UTC, happysalada commented
@nh2 curious to have your feebdack when you have a moment.

2021-04-05 19:17 UTC, SuperSandro2000 requested changes

2021-04-05 19:17 UTC, SuperSandro2000 commented on hosters/hetzner-dedicated/zfs-uefi-nvme-nixos.sh
> +apt install -y sudo parted zfs-dkms zfsutils-linux
```suggestion
apt install -y dpkg-dev linux-headers-$(uname -r) linux-image-amd64 sudo parted zfs-dkms zfsutils-linux
```

2021-04-05 19:17 UTC, SuperSandro2000 commented on hosters/hetzner-dedicated/zfs-uefi-nvme-nixos.sh
> +set -x
```suggestion
set -euox pipefail
```

2021-04-05 19:17 UTC, SuperSandro2000 commented on hosters/hetzner-dedicated/zfs-uefi-nvme-nixos.sh
> +set -e
```suggestion
umount /mnt || true
vgchange -an || true
```

2021-04-06 01:50 UTC, happysalada commented
@SuperSandro2000 Thanks for spending time on this!

2021-04-09 05:57 UTC, happysalada commented
@adisbladis sorry to bother you with this. I don't know who to contact to try to get this merged.
I'm actualy interested in being a maintainer for this repo.
If there is a way to get merge rights, I would be interested.

2021-04-09 12:58 UTC, merged

2021-04-09 13:00 UTC, zimbatm commented
Sounds good, I will make you a maintainer. If @nh2 springs back to life we can have a conversation with him.

2021-04-09 13:01 UTC, zimbatm commented
Check your emails for the invite!

2021-04-09 14:00 UTC, happysalada commented
@zimbatm thank you so much for the invite!